name: CD

on:
#  TODO: change from pull_request: to push:
#  This is only for testing purposes
  pull_request:
    branches: [ main ]


jobs:
  push_to_ecr:
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read  # This is required for actions/checkout

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: github-ecr-poweruser
          aws-region: us-east-1

      - name: Login to ECR
        run: aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/o8i6i1a1

      - name: Build docker image
        run: docker build -t shorturl/shorturl-be .

      - name: Tag built image
        run: |
          docker tag shorturl/shorturl-be:latest public.ecr.aws/o8i6i1a1/shorturl/shorturl-be:latest
#          TODO: add back in when pushing to main
#          docker tag shorturl/shorturl-be:${{ github.sha }} public.ecr.aws/o8i6i1a1/shorturl/shorturl-be:${{ github.sha }}

      - name: Push tagged images
        run: |
          docker push public.ecr.aws/o8i6i1a1/shorturl/shorturl-be:latest
#          TODO: add back in when pushing to main
#          docker push public.ecr.aws/o8i6i1a1/shorturl/shorturl-be:${{ github.sha }}